import { useState } from 'react';
import { useDispatch } from 'react-redux';
import { useNavigate } from 'react-router';
import { setCurrentUser } from '../features/user/userSlice';
import { setGlobalLoading } from '../features/ui/uiSlice';
import { setOnlineUsers } from '../features/chat/chatSelectionSlice';
import toastHelper from '../utils/toastHelper';
import authService from '../services/authService';

/**
 * LANDING PAGE COMPONENT
 * 
 * Why this page exists:
 * - Serves as the portal for entering a unique User ID.
 * - Simulates the login process: we do not use password checks; the ID itself is the identity.
 * - Stores the user ID in Redux upon verification and redirects the client to the `/chat` route.
 * 
 * Educational Integration Panel:
 * - Contains demo triggers for Toast notifications, showcasing how the frontend will display
 *   real-time events generated by Spring Boot / WebSocket callbacks later.
 */
export const LandingPage = () => {
  const dispatch = useDispatch();
  const navigate = useNavigate();
  const [userIdInput, setUserIdInput] = useState('');

  const handleJoin = async (e) => {
    e.preventDefault();
    const targetId = userIdInput.trim();

    if (!targetId) {
      toastHelper.error('User ID is required to join the chat.');
      return;
    }

    if (targetId.length < 3) {
      toastHelper.error('User ID must be at least 3 characters.');
      return;
    }

    // 1. Show global page loader to simulate connection handshake
    dispatch(setGlobalLoading(true));
    toastHelper.connection.connecting();

    try {
      // 2. Request authentication service verification
      const verifyResponse = await authService.verifyUser(targetId);

      // Store verified user details in Redux
      dispatch(setCurrentUser({
        userId: verifyResponse.userId,
        nickname: verifyResponse.nickname,
        avatarUrl: verifyResponse.avatarUrl
      }));

      // Set online users as empty list since it is a new session
      dispatch(setOnlineUsers([]));

      // Trigger success notifications
      toastHelper.connection.connected(verifyResponse.userId);

      // Redirect to the chat portal workspace
      navigate('/chat');
    } catch (error) {
      // Clear current session details
      toastHelper.error(error.message || 'Authentication handshake failed.');
      toastHelper.connection.error(error.message || 'Connection failed.');
    } finally {
      dispatch(setGlobalLoading(false));
    }
  };

  // Toast simulations for testing notification layout
  const triggerDemoToast = (type) => {
    switch (type) {
      case 'success':
        toastHelper.success('Operation completed successfully!');
        break;
      case 'error':
        toastHelper.error('Spring Boot API returned a 500 Internal Server Error.');
        break;
      case 'info':
        toastHelper.info('Database backup will start in 5 minutes.');
        break;
      case 'ws_connecting':
        toastHelper.connection.connecting();
        break;
      case 'ws_connected':
        toastHelper.connection.connected(userIdInput || 'GuestUser');
        break;
      case 'ws_disconnected':
        toastHelper.connection.disconnected();
        break;
      case 'ws_error':
        toastHelper.connection.error('STOMP Frame decode failed');
        break;
      case 'user_online':
        toastHelper.user.connected('Rahul');
        break;
      case 'user_offline':
        toastHelper.user.disconnected('Rahul');
        break;
      case 'msg_unread':
        toastHelper.chat.newMessage('Aman', 'Hey, did you get a chance to review the API schema?');
        break;
      default:
        break;
    }
  };

  return (
    <div className={`w-screen min-h-screen flex flex-col justify-between p-6 bg-slate-50 dark:bg-slate-950 text-slate-800 dark:text-slate-100 transition-colors duration-300`}>
      
      {/* Spacer / Top Header */}
      <header className="flex justify-end select-none">
        <span className="text-xs font-semibold tracking-wider text-slate-400 dark:text-slate-500 uppercase">
          Build v1.0.0
        </span>
      </header>

      {/* Main card panel wrapper */}
      <main className="w-full max-w-md mx-auto my-auto">
        <div className="
          p-8 rounded-3xl bg-white dark:bg-slate-900 
          border border-slate-200/60 dark:border-slate-800/80
          shadow-2xl transition-all duration-300
        ">
          {/* Logo Section */}
          <div className="flex flex-col items-center text-center mb-8">
            <div className="
              w-14 h-14 rounded-2xl bg-indigo-600 dark:bg-indigo-500 
              flex items-center justify-center text-white shadow-lg mb-4
            ">
              <svg className="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" />
              </svg>
            </div>
            <h1 className="text-2xl font-bold tracking-tight text-slate-900 dark:text-white">
              Welcome to ChatApp
            </h1>
            <p className="text-xs text-slate-400 dark:text-slate-500 mt-1.5 max-w-[250px]">
              Enter a unique User ID to begin secure, real-time conversations.
            </p>
          </div>

          {/* Form input block */}
          <form onSubmit={handleJoin} className="space-y-4">
            <div>
              <label 
                htmlFor="user-id-input" 
                className="block text-xs font-bold uppercase tracking-wider text-slate-400 dark:text-slate-500 mb-2"
              >
                Enter Unique User ID
              </label>
              <input
                id="user-id-input"
                type="text"
                value={userIdInput}
                onChange={(e) => setUserIdInput(e.target.value)}
                placeholder="e.g. rahul_99, aman_dev"
                autoFocus
                className="
                  w-full px-4 py-3 text-sm
                  bg-slate-50 dark:bg-slate-950
                  border border-slate-200 dark:border-slate-800
                  focus:border-indigo-500 dark:focus:border-indigo-500/80
                  text-slate-900 dark:text-slate-100
                  placeholder-slate-400 dark:placeholder-slate-500
                  rounded-2xl focus:outline-hidden
                  transition-all duration-200
                "
              />
            </div>

            <button
              type="submit"
              className="
                w-full py-3.5 rounded-2xl font-semibold text-sm cursor-pointer
                bg-indigo-600 hover:bg-indigo-500 text-white shadow-md active:scale-98
                transition-all duration-200 flex items-center justify-center gap-2
              "
            >
              <span>Join Messenger Workspace</span>
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M14 5l7 7m0 0l-7 7m7-7H3" />
              </svg>
            </button>
          </form>
        </div>

        {/* 
          EDUCATIONAL DEMO NOTIFICATION PANEL
          This helps the backend developer inspect Toast notification UI elements before WS binding.
        */}
        <div className="
          mt-6 p-5 rounded-2xl bg-slate-100 dark:bg-slate-900/40 
          border border-slate-200/50 dark:border-slate-800/40 text-center
        ">
          <span className="text-[10px] font-bold tracking-wider text-slate-400 dark:text-slate-500 uppercase block mb-3">
            Developer Live Toast Simulations
          </span>
          <div className="grid grid-cols-2 gap-2 text-[11px]">
            <button 
              onClick={() => triggerDemoToast('success')} 
              className="p-1.5 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-850 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-lg cursor-pointer"
            >
              Success Alert
            </button>
            <button 
              onClick={() => triggerDemoToast('error')} 
              className="p-1.5 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-850 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-lg cursor-pointer"
            >
              Error Alert
            </button>
            <button 
              onClick={() => triggerDemoToast('info')} 
              className="p-1.5 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-850 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-lg cursor-pointer"
            >
              Info Alert
            </button>
            <button 
              onClick={() => triggerDemoToast('ws_connecting')} 
              className="p-1.5 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-850 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-lg cursor-pointer"
            >
              WS Connecting
            </button>
            <button 
              onClick={() => triggerDemoToast('ws_connected')} 
              className="p-1.5 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-850 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-lg cursor-pointer"
            >
              WS Connected
            </button>
            <button 
              onClick={() => triggerDemoToast('ws_disconnected')} 
              className="p-1.5 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-850 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-lg cursor-pointer"
            >
              WS Disconnected
            </button>
            <button 
              onClick={() => triggerDemoToast('ws_error')} 
              className="p-1.5 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-850 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-lg cursor-pointer"
            >
              WS Connection Error
            </button>
            <button 
              onClick={() => triggerDemoToast('user_online')} 
              className="p-1.5 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-850 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-lg cursor-pointer"
            >
              Peer Presence Joined
            </button>
            <button 
              onClick={() => triggerDemoToast('user_offline')} 
              className="p-1.5 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-850 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-lg cursor-pointer"
            >
              Peer Presence Left
            </button>
            <button 
              onClick={() => triggerDemoToast('msg_unread')} 
              className="p-1.5 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-850 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-lg cursor-pointer"
            >
              WS Unread Message
            </button>
          </div>
        </div>
      </main>

      {/* Footer Info */}
      <footer className="text-center text-[10px] text-slate-400 dark:text-slate-500 font-medium select-none">
        Powered by React, Redux Toolkit, Context API & Tailwind CSS
      </footer>
    </div>
  );
};

export default LandingPage;
